@startuml Moto
class Moto {
-cilindrada : int
-peso : int
-alturaAsiento : double
-tipoTransmision : TipoTransmision
}

enum TipoTransmision {
  MANUAL
  AUTOMATICA
}
Moto --|> Vehiculo
Moto --> TipoTransmision

@enduml